replicaCount: 3

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

config:
  appEnv: development
  appName: kubernetes-web-app

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5

  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
